services:
  postgres:
    image: postgres:17
    container_name: eventflow_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER} -d ${DB_NAME}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - eventflow_network

  redis:
    image: redis:8-alpine
    container_name: eventflow_redis
    restart: unless-stopped

    command:
      - redis-server
      - --appendonly
      - "yes"

    volumes:
      - redis_data:/data

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

    networks:
      - eventflow_network

  backend:
    image: ghcr.io/akshatshrivastava0104/eventflow-api:latest
    container_name: eventflow_backend
    restart: unless-stopped

    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}

      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

      REDIS_HOST: redis
      REDIS_PORT: 6379

      JWT_SECRET: ${JWT_SECRET}

    ports:
      - "127.0.0.1:8080:8080"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 -O /dev/null http://127.0.0.1:8080/health || exit 1"
        ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - eventflow_network

networks:
  eventflow_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: