import { useState } from 'react';

interface QRCodeProps {
  value?: string | null;
  qrCodeUrl?: string | null;
  size?: number;
}

/**
 * Displays a real, machine-scannable QR code.
 *
 * The backend provides qr_code_url, which points to the
 * QR image generated from the EventFlow ticket payload.
 *
 * `value` is kept as a fallback so existing usages of this
 * component do not immediately break.
 */
export function QRCode({
  value,
  qrCodeUrl,
  size = 200,
}: QRCodeProps) {
  const [imageError, setImageError] = useState(false);

  /*
   * Prefer the QR URL generated by the backend.
   */
  if (qrCodeUrl && !imageError) {
    return (
      <img
        src={qrCodeUrl}
        alt={
          value
            ? `Ticket QR code ${value}`
            : 'Ticket QR code'
        }
        width={size}
        height={size}
        onError={() => {
          setImageError(true);
        }}
        className="rounded-lg object-contain"
        style={{
          width: size,
          height: size,
        }}
      />
    );
  }

  /*
   * Do not generate a fake QR code.
   */
  return (
    <div
      className="flex items-center justify-center rounded-lg bg-white"
      style={{
        width: size,
        height: size,
      }}
      role="img"
      aria-label="Ticket QR code pending"
    >
      <span className="px-4 text-center text-sm font-medium text-gray-500">
        {imageError
          ? 'QR code unavailable'
          : 'Ticket pending'}
      </span>
    </div>
  );
}