ALTER TABLE events
DROP COLUMN IF EXISTS allow_waitlist,
DROP COLUMN IF EXISTS max_tickets_per_user,
DROP COLUMN IF EXISTS visibility,
DROP COLUMN IF EXISTS featured,
DROP COLUMN IF EXISTS tags,
DROP COLUMN IF EXISTS cover_image,
DROP COLUMN IF EXISTS country,
DROP COLUMN IF EXISTS city,
DROP COLUMN IF EXISTS address,
DROP COLUMN IF EXISTS slug;